server:
  port: 8080

# Java 코드 기반 route 사용을 위해 일단 주석처리
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: backend-server
#          uri: http://localhost:8081
#          predicates:
#            - Path=/hello

spring:
  cloud:
    gateway:
      routes:
        - id: backend-service
          uri: lb://backend-service
          predicates:
            - Path=/hello

  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5433/gateway
    username: admin
    password: 1234

#  Entity 만들면  테이블 자동 생성
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

admin:
  key: super-admin-key