spring:
  application:
    name: test-service

server:
  port: 8181

# 게이트웨이 등록 설정
pine-gw:
  url: https://localhost:8080  # 게이트웨이 주소
  service-id: test-service     # 콘솔에서 보일 서비스 ID
  host: 127.0.0.1              # 게이트웨이가 이 서비스에 접근할 IP
  route:
    path: /test-dynamic/**             # 이 경로로 오는 요청을 test-service로 라우팅
    method: ALL
    priority: 0
